"""Central path definitions for the DC4 positron-analysis workflow.

This module only describes where files are located. Importing it does not
download, create, decompress, or overwrite any file.

Naming convention
-----------------
``*_remote_path``
    Location in the Wasabi data repository.
``*_path`` or ``*_paths``
    Location in the local workflow directory.
"""

from pathlib import Path


# -----------------------------------------------------------------------------
# Workflow directories
# -----------------------------------------------------------------------------

# Resolve the workflow directory from this file location.
repo_root = Path(__file__).resolve().parents[1]

# Store downloaded inputs separately from products generated by the analysis.
data_dir = repo_root / "data" / "inputs"
data_dir_out = repo_root / "data" / "outputs"
plot_dir_out = repo_root / "plot_outputs"
config_dir = repo_root / "config"


# -----------------------------------------------------------------------------
# Remote data directories
# -----------------------------------------------------------------------------

# Base locations used to construct the Wasabi paths below.
dc4_remote_data_dir = "COSI-SMEX/DC4/Data"
dc3_extended_response_remote_dir = (
    "COSI-SMEX/DC3/Data/Responses/extended_source_response"
)


# -----------------------------------------------------------------------------
# Observation inputs
# -----------------------------------------------------------------------------

# Spacecraft orientation history shared by all observation weeks.
orientation_filename = (
    "DC4_final_530km_3_month_with_slew_15sbins_"
    "GalacticEarth_SAA.fits"
)
data_ori_path = data_dir / orientation_filename
orientation_remote_path = (
    f"{dc4_remote_data_dir}/Orientation/{orientation_filename}"
)

# Fourteen weekly event files. The dictionaries use week numbers as keys.
weekly_files = {
    i: f"dc4_mock_dataset_week_{i}_unbinned_data_filtered_with_SAAcut.fits.gz"
    for i in range(1, 15)
}
weekly_paths = {
    week: data_dir / filename
    for week, filename in weekly_files.items()
}
weekly_remote_paths = {
    week: f"{dc4_remote_data_dir}/Mock_Dataset/{filename}"
    for week, filename in weekly_files.items()
}


# -----------------------------------------------------------------------------
# Simulated background input
# -----------------------------------------------------------------------------

# This background-only simulation is used to validate the data-driven model.
simulated_background_filename = (
    "Total_DC4_BG_3months_unbinned_data_"
    "filtered_with_SAAcut_withSAAbck.fits.gz"
)
simulated_background_remote_path = (
    f"{dc4_remote_data_dir}/Backgrounds/"
    f"{simulated_background_filename}"
)
simulated_background_path = data_dir / simulated_background_filename

# -----------------------------------------------------------------------------
# Detector responses
# -----------------------------------------------------------------------------

# Standard detector responses for the 511 keV and continuum analyses.
responses = [
    "Response511.o4.e509_513.s20881894470591.m2555.filtered."
    "nonsparse.binnedimaging.imagingresponse.h5",
    "ResponseContinuum.o3.e100_10000.b10log.s10396905069491."
    "m2284.filtered.nonsparse.binnedimaging.imagingresponse.h5",
]
response_paths = [data_dir / filename for filename in responses]
response_remote_paths = [
    f"{dc4_remote_data_dir}/Responses/{filename}"
    for filename in responses
]
data_response511_path = response_paths[0]
data_responsecon_path = response_paths[1]

# Extended responses are downloaded as .h5.gz archives and used as
# decompressed .h5 files. Both local forms are listed explicitly.
extended_responses_gz = [
    "extended_source_response_511_merged.h5.gz",
    "extended_source_response_continuum_merged.h5.gz",
]
extended_response_archive_paths = [
    data_dir / filename
    for filename in extended_responses_gz
]
extended_response_remote_paths = [
    f"{dc3_extended_response_remote_dir}/{filename}"
    for filename in extended_responses_gz
]

extended_responses = [
    "extended_source_response_511_merged.h5",
    "extended_source_response_continuum_merged.h5",
]
extended_response_paths = [
    data_dir / filename
    for filename in extended_responses
]
data_ext_response511_path = extended_response_paths[0]
data_ext_responsecon_path = extended_response_paths[1]


# -----------------------------------------------------------------------------
# Generated binned-data products
# -----------------------------------------------------------------------------

# Fine-energy weekly histograms used to estimate the 511 keV background.
# These files still contain source and background events; they are not
# background-only simulations or final fitted background models.
background_511_binned_paths = {
    week: (
        data_dir_out
        / f"dc4_week_{week}_511_background_binned.hdf5"
    )
    for week in weekly_paths
}

# Background-only simulation binned into the final 509--513 keV window.
simulated_background_511_binned_filename =  (
    "simulated_total_background_511_binned.hdf5"
)

simulated_background_511_binned_path = (
    data_dir_out / simulated_background_511_binned_filename
)


# -----------------------------------------------------------------------------
# Modeled background input
# -----------------------------------------------------------------------------

modelled_background_filename = "background_model_511_combined_baseline_raw.hdf5"
modelled_background_path  = data_dir_out / modelled_background_filename

# -----------------------------------------------------------------------------
# Binning configuration files
# -----------------------------------------------------------------------------

# The 511 keV and continuum files are standard DATAIO configurations. The
# background file defines the auxiliary fine-energy binning used in notebook 02.
config_511_path = config_dir / "dataio_511.yaml"
config_continuum_path = config_dir / "dataio_continuum.yaml"
config_511_background_path = config_dir / "dataio_511_background.yaml"
