data_file: /Users/maura/Documents/COSI/data-challenge-4/workflow/data/inputs/dc4_mock_dataset_week_1_unbinned_data_filtered_with_SAAcut.fits.gz
ori_file: /Users/maura/Documents/COSI/data-challenge-4/workflow/data/inputs/DC4_final_530km_3_month_with_slew_15sbins_GalacticEarth_SAA.fits
unbinned_output: fits
time_bins: 7979954.851480961
energy_bins:
- 100.0
- 158.489
- 251.189
- 398.107
- 630.957
- 1000.0
- 1584.89
- 2511.89
- 3981.07
- 6309.57
- 10000.0
phi_pix_size: 6
nside: 8
scheme: RING
tmin: 1835487300.036206
tmax: 1843467254.887687
